# Generated by Django 4.2.4 on 2023-08-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_tabelapedido_itens_do_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapedido',
            name='itens_do_pedido',
            field=models.JSONField(null=True),
        ),
    ]
