# Generated by Django 4.2.4 on 2023-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_cliente_tabelapedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='phone1',
            new_name='telefone1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='phone2',
            new_name='telefone2',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
