# Generated by Django 4.2.4 on 2023-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(default=0)),
                ('data_pedido_real', models.DateField(default='')),
                ('nome', models.CharField(default='', max_length=255)),
                ('estado', models.CharField(default='', max_length=255)),
                ('cidade', models.CharField(default='', max_length=255)),
                ('cep', models.IntegerField(null=True)),
                ('telefone1', models.IntegerField(default=0)),
                ('telefone2', models.IntegerField(null=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('itens_do_pedido', models.CharField(default='', max_length=500)),
                ('valor_do_pedido', models.FloatField(default=0.0)),
                ('status_do_pedido', models.CharField(default='', max_length=50)),
                ('data_ultimo_status', models.DateField(default='')),
                ('codigo_vendedor', models.CharField(default='', max_length=255)),
                ('prazo_informado', models.IntegerField(default=0)),
                ('tipo_de_cliente', models.CharField(max_length=255, null=True)),
                ('data_envio', models.DateField(null=True)),
                ('data_aprovado', models.DateField(null=True)),
                ('data_prevista', models.DateField(null=True)),
                ('cpfcnpj', models.BigIntegerField(default=0)),
                ('cupom_utilizado', models.CharField(blank=True, max_length=255)),
                ('qtd_pedido', models.IntegerField(default=0)),
                ('status_recorrencia', models.CharField(default='', max_length=50)),
                ('id_cliente', models.IntegerField(default=0)),
                ('boleto', models.CharField(max_length=255, null=True)),
                ('vencimento', models.CharField(default='', max_length=255)),
                ('endereco_boleto', models.CharField(default='', max_length=255)),
                ('total_produto', models.FloatField(default=0.0)),
                ('total_frete', models.FloatField(default=0.0)),
                ('total_desconto', models.FloatField(default=0.0)),
                ('forma_pagamento', models.CharField(default='', max_length=50)),
                ('codigo_autorizacao', models.CharField(max_length=50, null=True)),
                ('comentario_aprovado', models.TextField(null=True)),
                ('unidades_vendidas', models.IntegerField(null=True)),
                ('prazo_adicional', models.IntegerField(null=True)),
            ],
        ),
    ]
