# Generated by Django 4.2.4 on 2023-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tabelapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapedido',
            name='cep',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
