# Generated by Django 4.2.4 on 2023-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_tabelapedido_telefone1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapedido',
            name='cpfcnpj',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
