# Generated by Django 4.2.4 on 2023-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_rename_phone1_cliente_telefone1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCustomizeable', models.BooleanField(default=True)),
                ('product_id', models.IntegerField()),
                ('product_code', models.CharField(max_length=20, null=True)),
                ('sku_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_name_html', models.CharField(max_length=255)),
                ('product_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_delivery_time', models.CharField(max_length=255, null=True)),
                ('image', models.URLField()),
                ('brand', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id_product', models.IntegerField(null=True)),
                ('external_id_sku', models.IntegerField(null=True)),
                ('is_kit', models.BooleanField()),
                ('products_kit', models.JSONField(null=True)),
                ('sku_code', models.CharField(max_length=20, null=True)),
                ('product_cross_docking', models.IntegerField()),
                ('attributes', models.JSONField(null=True)),
                ('cubing', models.JSONField(null=True)),
            ],
        ),
    ]
